In [32]:
import numpy as np

# Вариант 2

## 1. Сгенерировать матрицу размером 3x4, состоящую из целых чисел

In [33]:
"""
Генерируется матрица размером 3х4,
состоящая из целых чисел от -128 до 127.
"""
a = np.random.randint(-128, 128, (3, 4), np.int8)
print(a)

[[ -43  120 -123  114]
 [  40   -5   14  -56]
 [ -94 -101  -10  -94]]


## 2. Вывести на экран элемент с индексами [1, 2]

In [34]:
""" Выводится элемент матрицы с индексами [1, 2]. """
print(a[1, 2])

14


## 3. Вывести на экран второй столбец матрицы

In [35]:
""" Выводятся все элементы второго столбца. """
print(a[:, 1].reshape(-1, 1))

[[ 120]
 [  -5]
 [-101]]


## 4. Вывести на экран каждый второй элемент первого столбца матрицы

In [36]:
""" Выводится каждый второй элемент первого столбца. """
print(a[::2, 0].reshape(-1, 1))

[[-43]
 [-94]]


## 5. Изменить форму матрицы с 3x4 на 6x2

In [37]:
""" Форма матрицы меняется на 6х2. """
a = a.reshape(6, 2)
print(a)

[[ -43  120]
 [-123  114]
 [  40   -5]
 [  14  -56]
 [ -94 -101]
 [ -10  -94]]


## 6. Разделить каждый элемент матрицы на заданное число

In [38]:
""" Каждый элемент матрицы делится на заданное число. """
a = a / 2
a

array([[-21.5,  60. ],
       [-61.5,  57. ],
       [ 20. ,  -2.5],
       [  7. , -28. ],
       [-47. , -50.5],
       [ -5. , -47. ]])

## 7. Найти максимальный элемент в каждом столбце

In [39]:
""" Выводится максимальный элемент каждого столбца. """
a.max(axis=0)

array([20., 60.])

## 8. Найми минимальный элемент в первой строке

In [40]:
""" Выводится минимальный элемент первой строки. """
print(a[0].min())

-21.5


## 9. Заданный одномерный массив
Дан одномерный массив числовых значений, насчитывающий N элементов. Определить образуют ли элементы массива, расположенные перед первым отрицательным элементом, возрастающую последовательность

In [41]:
""" Задаётся одномерный массив, состоящий из целых чисел. """
r = np.array([1, 2, 3, 4, -5, 3])

""" Находится индекс первого отрицательного числа. """
f = np.nonzero(r < 0)[0][0]

"""
Определяется, образуют ли возрастающую последовательность числа,
расположенные до первого отрицательного числа.

С помощью функции diff получается массив разниц значений
между соседними элементами. Если набор чисел, образованный
функцией sign из этого массива, состоит только из единиц,
то последовательность возрастающая.
"""
print(np.all(np.sign(np.diff(r[:f])) == 1))

True


## 10. Заданная матрица
Дана матрица. Выяснить является ли сумма элементов, расположенных над нулями, чётным числом.

In [42]:
""" Задаётся матрица, состоящая из целых чисел. """
m = np.array([[4, 0, 4, 2],
              [0, 9, 0, 5],
              [8, 0, 7, 0]])

""" Транспонируется ранее заданная матрица. """
m = m.T

""" Получаются массивы с индексами нулевых элементов. """
z = np.nonzero(m == 0)
x, y = z[1], z[0]

"""
Все индексы по строкам уменьшаются на единицу.
Если индекс равен 0, то остаётся без изменений.
"""
x = x - (x != 0)

"""
Суммируются все числа, находящиеся слева от нулей,
и их сумма проверяется на чётность.
"""
print(np.sum(m[y, x]) % 2 == 0)

True
